export const baseUrl = "http://localhost:8000";
export const getQuestionsUrl = baseUrl + "/questions";
export const signupUrl = baseUrl + "/auth/signup";
export const loginUrl = baseUrl + "/auth/login";
export const logoutUrl = baseUrl + "/auth/logout";
export const profileUrl = baseUrl + "/auth/profile";
export const answerUrl = baseUrl + "/answers";
export const searchURL = baseUrl + "/search/?q=";
export const voteQuestionUrl = baseUrl + "/votes/question/";
export const voteAnswerUrl = baseUrl + "/votes/answer/";
